### ISSUE TITLE
Blank Screen on running yarn install and yarn start

### ISSUE THREAD

**Issue by nvinai** [ejdoh1/wallstreetbets#1]
Hey ejdoh1, 
I tried to yarn and yarn start but I got a blank screen upon running it, am i supposed to do anything more on it?

**Comment by ejdoh1** [comment]
Heya, yeah will update readme but you should see https://ejdoh1.github.io/wallstreetbets

**Comment by ejdoh1** [comment]
@nvinai updated readme. simply run `npm i && npm start` and you should be good
